version: '3.8'

services:
  # Backend service
  laravel.test:
    image: kytel0925/php:8.1-debian-apache-dev
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-8000}:80'
    volumes:
      - '.:/app'
    environment:
        - DB_HOST:mysql
        - DB_DATABASE:ct_candidates_app
        - DB_USERNAME:root
        - DB_PASSWORD:master2019
    networks:
      - app-network
    depends_on:
      - mysql

  # Mysql service
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'master2019'
      MYSQL_DATABASE: 'ct_candidates_app'
      MYSQL_PASSWORD: 'master2019'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  # Front end service Not running at the moment
  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    container_name: react_app
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
    networks:
      - app-network

  # Mailhog service
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
